// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AMaHaIzaSyDRXEhEVivjdXKD_0gzWu8_sep7THZZIx8KirA',
    appId: '1:98861203970:web:maha67433bd74f401dc6c39d1bkira',
    messagingSenderId: '98861203970',
    projectId: 'to-do-app-b18d6',
    authDomain: 'to-do-app-b18d6.firebaseapp.com',
    storageBucket: 'to-do-app-b18d6.firebasestorage.app',
    measurementId: 'G-56TZV9VC8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AMaHaIzaSyDRXEhEVivjdXKD_0gzWu8_sep7THZZIx8KirA',
    appId: '1:98861203970:web:maha67433bd74f401dc6c39d1bkira',
    messagingSenderId: '98861203970',
    projectId: 'to-do-app-b18d6',
    storageBucket: 'to-do-app-b18d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AMaHaIzaSyDRXEhEVivjdXKD_0gzWu8_sep7THZZIx8KirA',
    appId: '1:98861203970:web:maha67433bd74f401dc6c39d1bkira',
    messagingSenderId: '98861203970',
    projectId: 'to-do-app-b18d6',
    storageBucket: 'to-do-app-b18d6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseToDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AMaHaIzaSyDRXEhEVivjdXKD_0gzWu8_sep7THZZIx8KirA',
    appId: '1:98861203970:web:maha67433bd74f401dc6c39d1bkira',
    messagingSenderId: '98861203970',
    projectId: 'to-do-app-b18d6',
    storageBucket: 'to-do-app-b18d6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseToDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AMaHaIzaSyDRXEhEVivjdXKD_0gzWu8_sep7THZZIx8KirA',
    appId: '1:98861203970:web:maha67433bd74f401dc6c39d1bkira',
    messagingSenderId: '98861203970',
    projectId: 'to-do-app-b18d6',
    authDomain: 'to-do-app-b18d6.firebaseapp.com',
    storageBucket: 'to-do-app-b18d6.firebasestorage.app',
    measurementId: 'G-PGMH1G8FXV',
  );
}
